{
 "title": "Slojka/SLO: Детализация 30d",
 "description": "Доска детализации состояния SLO по услугам, по метрикам создаваемым sloth.dev - окно 30 дней.  Ниже описание переменных и аннотаций.\n== Переменные== \n* service - технический сервис в вашем каталоге сервисов; \n* slo - имя slo из файла sloth; \n* sli_window - интервалы для которых считается sli (набор окон/метрик создается sloth.dev автоматически и зависит от контрольного окна SLO, тут набор для окна в 30 дней); \n* min_burning_rate - минимальная кратность расхода бюджета ошибок (EBBR) по SLO от какой показывать графики SLI; \n* incident_service_name - имя сервиса инциденты которого показать на графиках (в идеале имя сервиса должно быть единым, тогда можно будет видеть инциденты по данному сервису на графиках SLI, эту метрику пишет система управления инцидентами, у нас еще не так потому оставлен ручной выбор)\n== Аннотации ==\nDeployments - включить показ данных о развертывании сервиса $service; \nIncidents - показывать данные об инцидентах сервиса $incident_service_name;",
 "tags": [
  "slo",
  "sli",
  "service levels",
  "sloth",
  "slo-dashboard",
  "slojka",
  "vseinstrumenti"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "${DS_NAME}" },
   {
    "name": "service",
    "query": {
     "query": "query_result((slo:objective:ratio{} * on(sloth_id) group_left()  count by (sloth_id)   (slo:period_error_budget_remaining:ratio{sloth_window=\"30d\"})))"
    }
   },
   {
    "name": "slo",
    "query": {
     "query": "query_result(( slo:objective:ratio{sloth_service=\"$service\"} * on(sloth_id) group_left()   count by (sloth_id)  (slo:period_error_budget_remaining:ratio{sloth_service=\"$service\", sloth_window=\"30d\"})))"
    }
   },
   { "name": "sli_window", "label": "SLI window", "query": "5m,30m,1h,2h,6h,1d,3d,7d,30d" },
   { "name": "min_burning_rate", "label": "Мин. EBBR", "query": "1" },
   {
    "name": "incident_service_name",
    "label": "Инциденты в сервисе",
    "query": {
     "query": "label_values(vi_incident,service_name)"
    }
   },
   { "name": "budget_window_days", "query": "30" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\r\n  <center>\r\n    SLO в окне ${budget_window_days} дней\r\n  <center>\r\n</h1>"
   }
  },
  {
   "title": "Сводка нарушений SLO для ${service}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "График превышений допустимого уровня ошибок (EEBR) > x${min_burning_rate}",
     "type": "timeseries",
     "description": "SLO в которых уровень ошибок выше допустимого ",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}",
       "legendFormat": "{{sloth_id}}"
      }
     ]
    },
    {
     "title": "SLO быстро расходующие бюджет ошибок (EBBR>${min_burning_rate}x)",
     "type": "table",
     "description": "SLO в которых уровень ошибок выше допустимого ",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 3 },
     "targets": [
      {
       "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}"
      }
     ]
    }
   ]
  },
  { "title": "SLO: ${service}-${slo}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "slo" },
  {
   "type": "text",
   "description": "Ссылка на документ описание SLO",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<a href=\"https://kb.vseinstrumenti.ru/dosearchsite.action?cql=siteSearch%20~%20%22%5C%22${service}-${slo}%5C%22%22\" title=\"Вы должны залогиниться в Confluence для просмотра этого документа\" \r\nstyle=\" padding: 1em; border: 1px #666 solid; color: rgb(192, 216, 255); text-align: center; display: block; margin-left: auto; margin-right: auto;  width: 100%\"\r\n>Открыть документацию SLO ⮫</a>"
   }
  },
  {
   "type": "stat",
   "description": "Идентификатор SLI/SLO",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1)\r\n#slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "${service}: ${slo}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Остаток бюджета ошибок за последние ${budget_window} дней (скользящее окно)",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\r\n  sum_over_time(\r\n    label_replace(\r\n       slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}, \"slo_version\", \"0\", \"slo_version\", \"\"\r\n    )[${budget_window_days}d:1h]\r\n  ) \r\n  / on(sloth_id, slo_version)\r\n  (\r\n    label_replace(\r\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\r\n      \"slo_version\", \"0\", \"slo_version\", \"\"\r\n    ) *on() group_left() (24 * ${budget_window_days})\r\n  )\r\n)",
     "legendFormat": "Остаток бюджета (последние ${budget_window_days}d) v{{slo_version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"page\"}) or on() vector(0)",
     "legendFormat": "Тревога"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"ticket\"}) OR on() vector(0)",
     "legendFormat": "Предупреждение"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Кратность превышения допустимого уровня ошибок (EBBR) - Во сколько раз уровень ошибок выше, чем допустимый уровень ошибок исходя из бюджета ошибок на окно SLO\n",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} or on() vector(0)",
     "legendFormat": "Кратность ошибок (EBBR)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Установленный целевой уровень обслуживания",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sloth_slo_info{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "SLO {{sloth_objective}}%"
    }
   ]
  },
  {
   "title": "SLI/SLO",
   "type": "timeseries",
   "description": "Значения показателя уровня обслуживания (SLI): ${service}-${slo}",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max(slo:sli_error:ratio_rate${sli_window}{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) OR on() vector(0))",
     "legendFormat": "SLI"
    },
    {
     "expr": "label_replace(\r\n    slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"},\r\n    \"slo_version\", \"0\", \"slo_version\", \"\"\r\n)",
     "legendFormat": "Objective (SLO v{{slo_version}})"
    },
    {
     "expr": "ALERTS{alertname=\"ServiceSLOViolation\", sloth_service=\"${service}\", sloth_slo=\"${slo}\",sloth_severity=\"page\"}",
     "legendFormat": "SLO Violation Alert Active"
    }
   ]
  },
  {
   "title": "Остаток бюджета (окно ${budget_window_days} дней)",
   "type": "timeseries",
   "description": "График показывает диаграмму остатка бюджета ошибок в скользящем окне за последние ${budget_window_days} дней ",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    label_replace(\n       slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}, \"slo_version\", \"0\", \"slo_version\", \"\"\n    )[${budget_window_days}d:1h]\n  ) \n  / on(sloth_id, slo_version)\n  (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * ${budget_window_days})\n  )\n)",
     "legendFormat": "Остаток (SLO v{{slo_version}})"
    }
   ]
  },
  {
   "title": "Кратность превышения допустимого уровня ошибок (EBBR)",
   "type": "heatmap",
   "description": "Вот сколько раз уровень ошибок больше по отношению к допустимому уровню ошибок (AER). \n\nAER в час = бюджет ошибок / (30д * 24ч) \n\nПример. \n- SLO = 99.9%, Бюджет ошибок = 0.1% \n- В месяце 30 дней, это 43,200 минут. Таким образом, 0.1% времени — это 43.2 минуты\n- Бюджет ошибок на час EB_1h = 43.2 минуты / 720 часов = 0.06 минуты (3.6 секунды)\n- Допустим, за последний час у вас было ERR_1h = 10 секунд ошибок\n- Кратность уровня ошибок (EBBR) = ERR_1h/EB_1h = 10c/3.6c = 2.78 \n\nEBBR > 1 — значит мы расходуем бюджет быстрее, чем ожидается, при сохранении такого уровня, бюджет кончится раньше, чем за 30 дней\n\n",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} >0 ",
     "legendFormat": "Скорость расхода"
    }
   ]
  },
  {
   "title": "Остаток бюджета за календарный месяц (справочно)",
   "type": "timeseries",
   "description": "График показывает сколько осталось бюджета ошибок в календарном месяце (начиная от 1 числа и до конца месяца) ",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n      label_replace(\n        slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n        \"slo_version\", \"0\", \"slo_version\", \"\"\n      )\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  )\n  / on(sloth_id, slo_version)\n  (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * days_in_month())\n  )\n)",
     "legendFormat": "Остаток реальный (SLO v{{slo_version}})"
    },
    {
     "expr": "1 - sum_over_time(\n  (\n    (1 / (days_in_month() * 24)) *\n    (month() == bool vector(${__to:date:M}))\n  )[32d:1h]\n)",
     "legendFormat": "Остаток при идеальных условиях"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Бюджета ошибок на календарный месяц осталось, отсчет от 1 до  28-31 числа (не скользящее окно!)",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n      label_replace(\n        slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n        \"slo_version\", \"0\", \"slo_version\", \"\"\n      )\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  )\n  / on(sloth_id, slo_version)\n  (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * days_in_month())\n  )\n)",
     "legendFormat": "Остаток бюджета (за календарный месяц) (SLO v{{slo_version}})"
    }
   ]
  }
 ]
}