{
 "title": "Slojka/SLO: Общая статистика",
 "description": "Высокоуровневый обзор всех SLO по метрикам sloth.dev",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth",
  "vseinstrumenti",
  "slojka",
  "slo-dashboard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "${DS_NAME}" },
   {
    "name": "service",
    "label": "SLO Service",
    "query": {
     "query": "label_values(slo:objective:ratio,sloth_service)"
    }
   },
   { "name": "min_burning_rate", "label": "Мин. EBBR", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Статистика для ${service}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "Количество service в SLO",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(sloth_slo_info{sloth_service=~\"${service}\"}) by (sloth_service))",
     "legendFormat": "Объектов наблюдения"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Количество SLO для ${service}",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sloth_slo_info{sloth_service=~\"${service}\"})",
     "legendFormat": "Количество SLO"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Есть ли сейчас вообще активные Тревоги по SLO для ${service}",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"page\",sloth_service=~\"${service}\"}) OR on() vector(0)",
     "legendFormat": "Есть тревоги по SLO"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Есть ли сейчас вообще активные Предупреждения по SLO для ${service}",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"ticket\",sloth_service=~\"${service}\"}) OR on() vector(0)",
     "legendFormat": "Есть предупреждения по SLO"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Средняя кратность превышения допустимого уровня ошибок (EBBR) по всем услугам сервиса(ов)",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slo:current_burn_rate:ratio{sloth_service=~\"${service}\"}>0)",
     "legendFormat": "Средний EBBR"
    }
   ]
  },
  { "title": "Обзор по SLO для ${service}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "График превышений допустимого уровня ошибок (EEBR) > x${min_burning_rate}",
   "type": "timeseries",
   "description": "Кратность превышения допустимого уровня ошибок по всем услугам для ${service}, где она более ${min_burning_rate}x.  \n*Кликните на значение графика, в меню есть ссылка для перехода к детализаци SLO*",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "SLO быстро расходующие бюджет ошибок (EBBR>${min_burning_rate}x) ",
   "type": "table",
   "description": "SLO, расходующие больше бюджета ошибок для ${service}, кратность выше ${min_burning_rate}x.  \n*Кликните на название, в меню есть ссылка для отображения общей статистики только этого сервиса отдельно*",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "Хронология соблюдения SLO для ${service}",
   "type": "state-timeline",
   "description": "Показывает в какие моменты SLO расходовали бюджет ошибок быстрее расчетной скорости.  **Хорошо <=1, Плохо > 1**.  \n*Кликните на график, в меню есть ссылка для перехода к детализаци SLO*",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "Остаток бюджета в окне на 30 дней для ${service}",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:period_error_budget_remaining:ratio{sloth_service=~\"${service}\"}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  }
 ]
}