{
 "title": "Slojka/SLO: Детализация 90d",
 "description": "Доска детализации состояния SLO по услугам (или CUJ), по метрикам создаваемым sloth.dev - контрольное окно 90 дней.  Ниже описание переменных и аннотаций.\n== Переменные== \n* service - технический сервис в вашем каталоге сервисов; \n* slo - имя slo из файла sloth; \n* sli_window - интервалы для которых считается sli (набор окон/метрик создается sloth.dev автоматически и зависит от контрольного окна SLO, тут набор для окна в 90 дней); \n* min_burning_rate - минимальная кратность расхода бюджета ошибок (EBBR) по SLO от какой показывать графики SLI; \n* incident_service_name - имя сервиса инциденты которого показать на графиках (в идеале имя сервиса должно быть единым, тогда можно будет видеть инциденты по данному сервису на графиках SLI, эту метрику пишет система управления инцидентами, у нас еще не так потому оставлен ручной выбор)\n== Аннотации ==\nDeployments - включить показ данных о развертывании сервиса $service; \nIncidents - показывать данные об инцидентах сервиса $incident_service_name;",
 "tags": [
  "slo",
  "sli",
  "service levels",
  "sloth",
  "slo-dashboard",
  "slojka",
  "vseinstrumenti"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "${DS_NAME}" },
   { "name": "budget_window_days", "label": "SLO Budget (d)", "query": "90" },
   {
    "name": "service",
    "query": {
     "query": "query_result((slo:objective:ratio{} * on(sloth_id) group_left()  count by (sloth_id)   (slo:period_error_budget_remaining:ratio{sloth_window=\"${budget_window_days}d\"})))"
    }
   },
   {
    "name": "slo",
    "query": {
     "query": "query_result(( slo:objective:ratio{sloth_service=\"$service\"} * on(sloth_id) group_left()   count by (sloth_id)  (slo:period_error_budget_remaining:ratio{sloth_service=\"$service\", sloth_window=\"${budget_window_days}d\"})))"
    }
   },
   {
    "name": "sli_window",
    "label": "SLI window",
    "query": {
     "query": "query_result(group by (sloth_window) ({__name__=~\"slo:sli_error:ratio_rate(.*?)\"}  * on(sloth_id) group_left() slo:period_error_budget_remaining:ratio{sloth_window=\"${budget_window_days}d\"}))"
    }
   },
   { "name": "min_burning_rate", "label": "Мин. EBBR", "query": "1" },
   {
    "name": "quarter_no",
    "label": "Текущий квартал №",
    "query": {
     "query": "query_result(floor(month()/4)+1)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\r\n  <center>\r\n    SLO в окне ${budget_window_days} дней / квартальные\r\n  <center>\r\n</h1>"
   }
  },
  {
   "title": "Сводка нарушений SLO для ${service}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "График превышений допустимого уровня ошибок (EEBR) > x${min_burning_rate}",
     "type": "timeseries",
     "description": "SLO в которых уровень ошибок выше допустимого ",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}",
       "legendFormat": "{{sloth_id}}"
      }
     ]
    },
    {
     "title": "SLO быстро расходующие бюджет ошибок (EBBR>${min_burning_rate}x)",
     "type": "table",
     "description": "SLO в которых уровень ошибок выше допустимого ",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
     "targets": [
      {
       "expr": "slo:current_burn_rate:ratio{sloth_service=~\"${service}\"} > ${min_burning_rate}"
      }
     ]
    }
   ]
  },
  { "title": "SLO: ${service}-${slo}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "slo" },
  {
   "type": "text",
   "description": "Ссылка на документ описание SLO",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<a href=\"https://confluence/dosearchsite.action?cql=siteSearch%20~%20%22%5C%22${service}-${slo}%5C%22%22\" title=\"Вы должны залогиниться в Confluence для просмотра этого документа\" \r\nstyle=\" padding: 1em; border: 1px #666 solid; color: rgb(192, 216, 255); text-align: center; display: block; margin-left: auto; margin-right: auto;  width: 100%\"\r\n>Открыть документацию SLO ⮫</a>"
   }
  },
  {
   "type": "stat",
   "description": "Идентификатор SLI/SLO",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1)\r\n#slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "${service}: ${slo}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Остаток бюджета ошибок за последние ${budget_window_days} дней (скользящее окно)",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\r\n  sum without (feature, title, sli_class) (sum_over_time(\r\n    label_replace(\r\n       slo:sli_error:ratio_rate15m{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}, \"slo_version\", \"0\", \"slo_version\", \"\"\r\n    )[${budget_window_days}d:15m]\r\n  )) \r\n  / on(sloth_id, slo_version)\r\n  sum without (feature, title, sli_class) (\r\n    label_replace(\r\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\r\n      \"slo_version\", \"0\", \"slo_version\", \"\"\r\n    ) *on() group_left() (24 * ${budget_window_days} * 4)\r\n  )\r\n)",
     "legendFormat": "Остаток бюджета (последние ${budget_window_days}) v{{slo_version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"page\"}) or on() vector(0)",
     "legendFormat": "Тревога"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"ticket\"}) OR on() vector(0)",
     "legendFormat": "Предупреждение"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Кратность превышения допустимого уровня ошибок (EBBR) - Во сколько раз уровень ошибок выше, чем допустимый уровень ошибок исходя из бюджета ошибок на окно SLO\n",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} or on() vector(0)",
     "legendFormat": "Кратность ошибок (EBBR)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Установленный целевой уровень обслуживания",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sloth_slo_info{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "SLO {{sloth_objective}}%"
    }
   ]
  },
  {
   "title": "SLI/SLO",
   "type": "timeseries",
   "description": "Значения показателя уровня обслуживания (SLI)",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max(slo:sli_error:ratio_rate${sli_window}{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) OR on() vector(0))",
     "legendFormat": "SLI"
    },
    {
     "expr": "label_replace(\r\n    slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"},\r\n    \"slo_version\", \"0\", \"slo_version\", \"\"\r\n)",
     "legendFormat": "Objective (SLO v{{slo_version}})"
    }
   ]
  },
  {
   "title": "Остаток бюджета (окно ${budget_window_days} дней) ",
   "type": "timeseries",
   "description": "График показывает диаграмму остатка бюджета ошибок в скользящем окне за последние ${budget_window_days} дней ",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum without (feature, title, sli_class) (sum_over_time(\n    label_replace(\n       slo:sli_error:ratio_rate15m{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}, \"slo_version\", \"0\", \"slo_version\", \"\"\n    )[${budget_window_days}d:15m]\n  )) \n  / on(sloth_id, slo_version)\n  sum without (feature, title, sli_class) (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * ${budget_window_days} * 4)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кратность превышения допустимого уровня ошибок (EBBR)",
   "type": "heatmap",
   "description": "Вот сколько раз уровень ошибок больше по отношению к допустимому уровню ошибок (AER). \n\nAER в час = бюджет ошибок / (30д * 24ч) \n\nПример. \n- SLO = 99.9%, Бюджет ошибок = 0.1% \n- В месяце 30 дней, это 43,200 минут. Таким образом, 0.1% времени — это 43.2 минуты\n- Бюджет ошибок на час EB_1h = 43.2 минуты / 720 часов = 0.06 минуты (3.6 секунды)\n- Допустим, за последний час у вас было ERR_1h = 10 секунд ошибок\n- Кратность уровня ошибок (EBBR) = ERR_1h/EB_1h = 10c/3.6c = 2.78 \n\nEBBR > 1 — значит мы расходуем бюджет быстрее, чем ожидается, при сохранении такого уровня, бюджет кончится раньше, чем за 30 дней\n\n",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} ",
     "legendFormat": "Скорость расхода"
    }
   ]
  },
  {
   "title": "Остаток бюджета за этот квартал - Q${quarter_no}",
   "type": "timeseries",
   "description": "График показывает сколько осталось бюджета ошибок на квартал Q${quarter_no}",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum without (feature, title, sli_class) (sum_over_time(\n    (\n      label_replace(\n        slo:sli_error:ratio_rate15m{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n        \"slo_version\", \"0\", \"slo_version\", \"\"\n      )\n       * on() group_left() (\n         (floor((month() - 1) / 3)  == bool floor((vector(${__to:date:M}) - 1) / 3))\n       )\n    )[32d:15m]\n  ))\n  / on(sloth_id, slo_version)\n  sum without (feature, title, sli_class) (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * ${budget_window_days} * 4)\n  )\n)",
     "legendFormat": "Остаток реальный (SLO v{{slo_version}})"
    },
    {
     "expr": "\n1 - sum_over_time(\n  (\n    (1 / (90 * 24)) *\n    (floor((month() - 1) / 3)  == bool floor((vector(${__to:date:M}) - 1) / 3))\n  )[96d:1h]\n)",
     "legendFormat": "Остаток при идеальных условиях"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Бюджета ошибок на календарный месяц осталось, отсчет от 1 до  28-31 числа (не скользящее окно!)",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n  sum without (feature, title, sli_class) (sum_over_time(\n    (\n      label_replace(\n        slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n        \"slo_version\", \"0\", \"slo_version\", \"\"\n      )\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  ))\n  / on(sloth_id, slo_version)\n  sum without (feature, title, sli_class) (\n    label_replace(\n      slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"},\n      \"slo_version\", \"0\", \"slo_version\", \"\"\n    ) *on() group_left() (24 * days_in_month())\n  )\n)",
     "legendFormat": "Остаток бюджета (за календарный месяц) (SLO v{{slo_version}})"
    }
   ]
  }
 ]
}