# Based on https://sre.google/workbook/alerting-on-slos/#recommended_parameters_for_an_slo_based_a
apiVersion: "sloth.slok.dev/v1"
kind: "AlertWindows"
spec:
  sloPeriod: 90d
  page:
    quick:
      errorBudgetPercent: 2
      shortWindow: 15m
      longWindow: 3h
    slow:
      errorBudgetPercent: 5
      shortWindow: 90m
      longWindow: 18h
  ticket:
    quick:
      errorBudgetPercent: 10
      shortWindow: 6h
      longWindow: 3d
    slow:
      errorBudgetPercent: 10
      shortWindow: 18h
      longWindow: 9d
